
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juvfuvamiszfyinyxlxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1dmZ1dmFtaXN6Znlpbnl4bHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODM0NTgsImV4cCI6MjA1OTQ1OTQ1OH0.OjGHWfASOl_2JlUbxXC7aMtBivUJFJoSSpaoF-GHzUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Add custom type definitions for our extended database schema
export type TwinDetail = {
  id: string;
  name: string;
  description: string | null;
  image_url: string | null;
  status: string | null;
  created_at: string;
  tags: string[] | null;
  features: Record<string, any> | null;
  model_data: Record<string, any> | null;
  processing_status: string | null;
  owner_id: string;
  updated_at: string;
  parent_id: string | null;
  related_twin_ids: string[] | null;
};

export type Category = {
  id: string;
  name: string;
  description?: string | null;
};
